In [26]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [20]:
df = pd.read_csv('raw/retail_fraud_detection_100k.csv')
df.head()

,transaction_id,customer_id,transaction_timestamp,transaction_amount,payment_method,device_type,location,merchant_category,is_international,transaction_frequency_24h,...,failed_transaction_count_24h,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag,fraud_risk
0,T0000001,C20953,2026-03-04 19:56:23.679173,56.31,Debit Card,Tablet,Canada,Fashion,0,13,...,4,1054,0,0,0,1,0,1,0,Medium
1,T0000002,C24133,2026-03-09 19:56:23.679330,20.35,Credit Card,Tablet,India,Electronics,0,3,...,2,97,0,0,0,0,0,0,0,Low
2,T0000003,C07165,2026-01-01 19:56:23.679362,48.72,Debit Card,Tablet,UK,Travel,0,8,...,4,779,1,0,0,0,0,0,0,Medium
3,T0000004,C19310,2025-12-09 19:56:23.679385,153.62,Debit Card,Mobile,Australia,Fashion,0,14,...,3,286,1,1,0,1,0,1,1,High
4,T0000005,C25019,2025-11-09 19:56:23.679409,115.32,PayPal,Mobile,India,Gaming,0,10,...,3,866,0,0,0,1,0,0,0,Low

In [21]:
df = df.drop(columns=['transaction_id', 'customer_id', 'transaction_timestamp', 'fraud_risk'])
df.shape

(100000, 17)

In [23]:
categorical_cols = ['payment_method', 'device_type', 'location', 'merchant_category']

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

,transaction_amount,payment_method,device_type,location,merchant_category,is_international,transaction_frequency_24h,avg_transaction_amount_7d,failed_transaction_count_24h,account_age_days,previous_fraud_flag,unusual_amount_flag,unusual_location_flag,multiple_transactions_short_time,high_risk_device_flag,velocity_flag,fraud_flag
0,56.31,2,2,1,1,0,13,53.02,4,1054,0,0,0,1,0,1,0
1,20.35,1,2,3,0,0,3,38.00,2,97,0,0,0,0,0,0,0
2,48.72,2,2,4,5,0,8,147.45,4,779,1,0,0,0,0,0,0
3,153.62,2,1,0,1,0,14,58.22,3,286,1,1,0,1,0,1,1
4,115.32,4,1,3,2,0,10,114.46,3,866,0,0,0,1,0,0,0

In [24]:
X = df.drop(columns='fraud_flag')
y = df['fraud_flag']

print(X.shape)
print(y.shape)

(100000, 16)
(100000,)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(X_train.shape)
print(X_test.shape)

(80000, 16)
(20000, 16)